CREATE TABLE employersV2 (
                        EMPLOYEE_ID INT(3) NOT NULL AUTO_INCREMENT,
                        FIRST_NAME VARCHAR(15) NOT NULL,
                        LAST_NAME VARCHAR(30) NOT NULL,
                        EMAIL VARCHAR(40) NOT NULL,
                        PHONE_NUMBER NUMBER NOT NULL,
                        HIRE_DATE DATE NOT NULL,
                        JOB_ID VARCHAR(15),
                        SALARY DECIMAL(10,2) NOT NULL,
                        COMMISSION_PCT DECIMAL(10,2) NOT NULL,
                        MANAGER_ID INT,
                        DEPARTAMENT_ID INT,
                        PRIMARY KEY(EMPLOYEE_ID)                     
                        );
INSERT INTO employersV2 (FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTAMENT_ID)
		VALUES ('Steven', 'King', 'SKING', 515.123, '1987-06-17', 'ADPRES', 24000.00, 0.00, 0, 90);
SELECT * from employersV2;
INSERT INTO employersV2 (FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTAMENT_ID)
		VALUES ('Neena', 'Kochhar', 'NKOCHHAR', 515.124, '1987-06-18', 'ADVP', 17000.00, 0.00, 100, 90);
INSERT INTO employersV2 (FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTAMENT_ID)
		VALUES ('Lex', 'De Haan', 'LDEHAAN', 515.125, '1987-06-19', 'ADVP', 17000.00, 0.00, 100, 90);
INSERT INTO employersV2 (FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTAMENT_ID)
		VALUES ('Alexander', 'Hunold', 'AHUNOLD', 590.126, '1987-06-20', 'ITPROG', 9000.00, 0.00, 102, 60);
INSERT INTO employersV2 (FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTAMENT_ID)
		VALUES ('Bruce', 'Ernst', 'BERNST', 590.127, '1987-06-21', 'ITPROG', 6000.00, 0.00, 103, 60);
INSERT INTO employersV2 (FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTAMENT_ID)
		VALUES ('David', 'Austin', 'Daustin', 590.128, '1987-06-22', 'ITPROG', 4800.00, 0.00, 103, 60);
INSERT INTO employersV2 (FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTAMENT_ID)
		VALUES ('Valli', 'Pataballa', 'VPATABAL', 590.129, '1987-06-23', 'ITPROG', 4800.00, 0.00, 103, 60);
INSERT INTO employersV2 (FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTAMENT_ID)
		VALUES ('Diana', 'Lorentz', 'DLORENTZ', 590.130, '1987-06-24', 'ITPROG', 4200.00, 0.00, 103, 60);

UPDATE employersV2 SET EMAIL='CANCELADO' WHERE DEPARTAMENT_ID = 60;
SELECT * FROM employersV2;
SELECT FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER FROM employersV2 ORDER BY FIRST_NAME;
SELECT SUM(SALARY) FROM employersV2;
SELECT CONCAT('O Funcionário ', FIRST_NAME,' ', LAST_NAME, ' foi contratado em: ', HIRE_DATE) FROM employersV2;
SELECT FIRST_NAME, SALARY FROM employersV2 WHERE SALARY > 5000.00 AND SALARY < 10000.00 AND DEPARTAMENT_ID = 60;
